name: Test

on:
  push:
    branch:
      - master
    paths:
      - websh
      - test
      - test.bats
      - .github/workflows/test.yml

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run Bash dryrun
      run: bash -n websh
    - name: Run ShellCheck
      uses: ludeeus/action-shellcheck@master
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install bats
      run : |
        sudo apt install bats -y
        ./websh "echo test1" | wc -l
    - name: Run tests
      run: bats test.bats
