name: Test

on:
  push:
    branch:
      - master
    paths:
      - websh
      - test
      - test.bats

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run Bash dryrun
      run: bash -n websh
    - name: Run ShellCheck
      uses: ludeeus/action-shellcheck@master
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install bats
      run : sudo apt install bats && bats -v
    - name: Test 1
      run: echo "$(./websh |& wc -l)"
  　- name: Test 2
      run: echo "$(./websh 'echo test' |& wc -l)"
    - name: Run tests
      run: bats test.bats
